from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='indexOfAccounts'),
    path('register/', views.register, name='register'),
    path('login/', views.connexion, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    #path('administration/', views.administration, name='administration'),
    path('search-family/', views.search_family, name='search_family'),
    path('join-request/<int:request_id>/approve/', views.approve_join_request, name='approve_join_request'),
    path('join-request/<int:request_id>/reject/',  views.reject_join_request,  name='reject_join_request'),
    path('member/<int:user_id>/remove/',           views.remove_member,        name='remove_member'),
    path('family/edit/',                           views.edit_family,          name='edit_family'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('members/', views.members_list, name='members_list'),
    path('members/<int:member_id>/', views.member_profile, name='member_profile'),
    path('search-members/', views.search_members, name='search_members'),
    path('relations/add/', views.add_relation, name='add_relation'),
    path('relations/<int:relation_id>/delete/', views.delete_relation, name='delete_relation'),
    path('family-tree/', views.family_tree, name='family_tree'),
    path('feed/', views.news_feed, name='news_feed'),
    path('feed/post/create/', views.create_post, name='create_post'),
    path('feed/post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('feed/post/<int:post_id>/react/', views.toggle_reaction, name='toggle_reaction'),
    path('feed/post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('calendar/', views.calendar_view, name='calendar_view'),
    path('calendar/event/create/', views.create_event, name='create_event'),
    path('calendar/event/<int:event_id>/delete/', views.delete_event, name='delete_event'),
    path('calendar/event/<int:event_id>/rsvp/', views.rsvp_event, name='rsvp_event'),
    path('relation-request/<int:request_id>/accept/', views.accept_relation_request, name='accept_relation_request'),
    path('relation-request/<int:request_id>/reject/', views.reject_relation_request, name='reject_relation_request'),
    path('notifications/',                        views.notifications,           name='notifications'),
    path('notifications/<int:notif_id>/read/',    views.mark_notification_read,  name='mark_notification_read'),
    path('media/', views.media_library, name='media_library'),
    path('media/album/create/', views.create_album, name='create_album'),
    path('media/album/<int:album_id>/', views.album_detail, name='album_detail'),
    path('media/album/<int:album_id>/upload/', views.upload_media, name='upload_media'),
    path('media/album/<int:album_id>/delete/', views.delete_album, name='delete_album'),
    path('timeline/', views.timeline_view, name='timeline_view'),
    path('timeline/create/', views.create_timeline_event, name='create_timeline_event'),
    path('timeline/<int:event_id>/delete/', views.delete_timeline_event, name='delete_timeline_event'),
]