# Generated by Django 6.0.5 on 2026-06-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_family_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.family'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='relation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
