# Generated by Django 6.0.5 on 2026-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_family_alter_joinrequest_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
