# Generated by Django 6.0.5 on 2026-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_family_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
