# Generated by Django 6.0.5 on 2026-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banner',
        ),
        migrations.AddField(
            model_name='family',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Bannieres/'),
        ),
    ]
