# Generated by Django 6.0.5 on 2026-06-24 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_banner_family_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relation_to_family',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('parent', 'Parent'), ('enfant', 'Enfant'), ('conjoint', 'Conjoint(e)'), ('frere_soeur', 'Frère / Sœur'), ('cousin', 'Cousin(e)'), ('grand_parent', 'Grand-parent'), ('petit_enfant', 'Petit-enfant'), ('oncle_tante', 'Oncle / Tante'), ('neveu_niece', 'Neveu / Nièce'), ('autre', 'Autre')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to=settings.AUTH_USER_MODEL)),
                ('related_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('member', 'related_member')},
            },
        ),
    ]
