# Generated by Django 6.0.5 on 2026-06-24 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_event_rsvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('parent', 'Parent'), ('enfant', 'Enfant'), ('conjoint', 'Conjoint(e)'), ('frere_soeur', 'Frère / Sœur'), ('cousin', 'Cousin(e)'), ('grand_parent', 'Grand-parent'), ('petit_enfant', 'Petit-enfant'), ('oncle_tante', 'Oncle / Tante'), ('neveu_niece', 'Neveu / Nièce'), ('autre', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_relation_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_relation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
