# Generated by Django 6.0.5 on 2026-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('relation_request', 'Demande de relation'), ('relation_accepted', 'Relation acceptée'), ('relation_rejected', 'Relation refusée'), ('join_approved', 'Adhésion approuvée'), ('new_post', 'Nouvelle publication'), ('new_comment', 'Nouveau commentaire'), ('new_like', 'Nouveau like'), ('new_event', 'Nouvel événement'), ('birthday', 'Anniversaire')], max_length=30),
        ),
    ]
