# Generated by Django 6.0.5 on 2026-06-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
    ]
