# Generated by Django 6.0.5 on 2026-06-26 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_joinrequest_attempt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('modify', 'Modification'), ('delete', 'Suppression')], max_length=10)),
                ('new_relation_type', models.CharField(blank=True, choices=[('parent', 'Parent'), ('enfant', 'Enfant'), ('conjoint', 'Conjoint(e)'), ('frere_soeur', 'Frère / Sœur'), ('cousin', 'Cousin(e)'), ('grand_parent', 'Grand-parent'), ('petit_enfant', 'Petit-enfant'), ('oncle_tante', 'Oncle / Tante'), ('neveu_niece', 'Neveu / Nièce'), ('autre', 'Autre')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='accounts.relation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
