# Generated by Django 6.0.5 on 2026-06-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_relationchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_birth_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_profession',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
