# Generated by Django 6.0.5 on 2026-06-26 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_city_user_hide_birth_date_user_hide_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deceased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deceased_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_deceased', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
    ]
