# Generated by Django 6.0.5 on 2026-06-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_guestaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guestaccess',
            unique_together={('guest', 'family')},
        ),
    ]
