# Generated by Django 6.0.5 on 2026-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_guestaccess_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('member', 'Membre')], default='member', max_length=20),
        ),
    ]
