# Generated by Django 6.0.5 on 2026-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_directaddrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('relation_request', 'Demande de relation'), ('relation_accepted', 'Relation acceptée'), ('relation_rejected', 'Relation refusée'), ('join_approved', 'Adhésion approuvée'), ('new_post', 'Nouvelle publication'), ('new_comment', 'Nouveau commentaire'), ('new_like', 'Nouveau like'), ('new_event', 'Nouvel événement'), ('birthday', 'Anniversaire'), ('removal_vote', 'Vote de retrait'), ('removal_vote_target', 'Vote de retrait — vous concerne')], max_length=30),
        ),
    ]
